### ISSUE TITLE
App is force closing!!

### ISSUE THREAD

**Issue by abhishekds94** [crazyhitty/firebase-chat#11]
Hey, I followed your instructions from your updated Readme file. Login and Registrations are happening and are also being reflected in the Console. But the issue is that after the login when app goes to the screen where it will display the users available, there the app is getting crashed.

The below is the logcat. Can you assist me with this?

                                                                                      Process: com.crazyhitty.chdev.ks.firebasechat, PID: 12649
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
                                                                                          at com.crazyhitty.chdev.ks.firebasechat.ui.adapters.UserListingRecyclerAdapter.onBindViewHolder(UserListingRecyclerAdapter.java:42)
                                                                                          at com.crazyhitty.chdev.ks.firebasechat.ui.adapters.UserListingRecyclerAdapter.onBindViewHolder(UserListingRecyclerAdapter.java:20)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5825)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5858)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5094)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                                          at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                          at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
                                                                                          at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:846)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                                          at android.view.View.layout(View.java:16001)
                                                                                      	at android.view.ViewGroup.layout(ViewGroup.java:5181

@crazyhitty

**Comment by francogrex** [comment]
Why is this issue closed without explanation (of the solution that lead to its closure). Please provide the necessary info for transparency.
